// Generated by script/generate_legal_documents.swift.
// Edit the canonical root documents, then run the generator.

enum GeneratedLegalDocumentSources {
    static let termsOfUseMarkdown = #"""
# Terms of Use

These terms explain the conditions for using a prebuilt copy of Swiftea distributed by the Developer with a compatible Ember Mug. Please read them together with the Safety Notice.

**Version 1.0 · Effective July 18, 2026**

## 1. Agreement

These Terms of Use are an agreement between you and Tomás Papi, Swiftea’s independent developer and maintainer (the “Developer”). They apply to prebuilt copies of Swiftea distributed by the Developer. By selecting the agreement checkbox and using Swiftea, you confirm that you have read, understood, and agreed to these terms and the Safety Notice. Sections 5–7 and 11–13 are especially important: they explain risks of severe harm, software and Bluetooth limitations, your safety responsibilities, warranty disclaimers, an assumption of risk, a release of certain claims (including certain ordinary-negligence claims), and limits on liability. Each of those provisions applies only to the extent permitted by law. If you do not agree, do not use Swiftea.

## 2. Open-source license

Swiftea’s source code is offered under the Zero-Clause BSD License (0BSD). That license governs permission to use, copy, modify, and distribute the source code. These terms do not take away rights granted by 0BSD. They address prebuilt copies distributed by the Developer, their interaction with physical hardware, and the related safety and liability terms to the extent permitted by law. A modified or independently distributed build is the responsibility of whoever creates or distributes it.

## 3. Unofficial, independent software

Swiftea is an independent project. It is not affiliated with, sponsored by, authorized by, or endorsed by Ember Technologies, Inc. Ember, Ember Mug, Ember Mug 2, and related names and marks belong to their respective owners. The Developer does not manufacture, sell, warrant, repair, or control the mug, charging coaster, firmware, battery, or other Ember products.

## 4. Intended use and eligibility

Swiftea is a personal utility for controlling a compatible Ember Mug that you own or are authorized to use. It is not a safety system, medical device, commercial temperature-control system, or substitute for supervising hot liquids and electrical products. You must be legally able to enter this agreement. If you are not an adult under the law where you live, a parent or legal guardian must review and accept these terms for you.

## 5. Heated-hardware risks

An Ember Mug contains a heating element, hot liquid, a rechargeable battery, electronics, and charging equipment. Using it can involve burns, spills, overheating, fire, electrical hazards, property damage, battery failure, serious bodily injury, or death, as well as damage to the mug and nearby objects. Do not use Swiftea or a heated mug unattended, while sleeping, near flammable materials, or in any situation where a delayed or failed shutoff could cause harm. Keep children and pets appropriately supervised. Always follow Ember’s current manuals, warnings, care instructions, safety notices, and recalls.

## 6. Software and Bluetooth limitations

Swiftea is unofficial software and may contain bugs, defects, coding errors, omissions, or unintended behavior. It may send a delayed, repeated, incorrect, or unintended command; fail to send or stop a command; misread or misreport the mug’s state; or affect the mug in a way the Developer did not foresee. These events can occur even when you use Swiftea correctly and follow every instruction. Bluetooth can also fail, disconnect, reconnect, lag, or be interrupted by another app, another device, macOS sleep, radio interference, firmware behavior, or hardware conditions. Automatic shutoff, automatic reconnection, notifications, history, and other automation may fail. Never rely on Swiftea to prevent burns, serious bodily injury, death, fire, property damage, or any other unsafe condition.

## 7. Your responsibilities

You are responsible for checking the physical mug and its surroundings, choosing a safe target temperature, and confirming that heating and charging behave as expected. Stop using and disconnect the mug if it is damaged, leaking, unusually hot, smoking, producing an unusual smell, behaving unexpectedly, or showing a state that conflicts with Swiftea. Never microwave an Ember Mug. Dry it completely before placing it on a charging coaster, and use compatible official charging equipment as directed by Ember. Do not use Swiftea for unlawful, hazardous, abusive, or safety-critical purposes.

## 8. Multiple controllers and account security

An Ember Mug generally accepts one active controller at a time. Close other apps that may control the same mug before using Swiftea. You are responsible for access to your Mac and for changes made through Swiftea while your user account is open.

## 9. Local data and update checks

Swiftea does not require an account and does not include developer-operated analytics or telemetry. It stores preferences, saved mug details, and limited mug history locally on your Mac. When update checks are enabled or started manually, Sparkle contacts Swiftea’s public update feed and may contact GitHub-hosted release infrastructure. Those third parties may receive ordinary network information such as your IP address and request metadata under their own policies. You are responsible for backing up or deleting local app data if that matters to you.

## 10. Updates, availability, and support

Swiftea may change, stop supporting a macOS version or mug behavior, or be discontinued at any time. Updates may add, remove, or change features. The Developer does not promise continuous availability, compatibility, security updates, bug fixes, support, or recovery of local data. You may stop using Swiftea at any time.

## 11. No warranties

TO THE FULLEST EXTENT PERMITTED BY LAW, SWIFTEA IS PROVIDED “AS IS” AND “AS AVAILABLE”, WITHOUT WARRANTIES OR GUARANTEES OF ANY KIND. THE DEVELOPER DISCLAIMS ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, RELIABILITY, SAFETY, COMPATIBILITY, AND UNINTERRUPTED OR ERROR-FREE OPERATION. No statement or feature in Swiftea creates a warranty. Any mandatory warranty or guarantee that applicable law does not allow to be excluded remains in effect.

## 12. Assumption of risk and release

You knowingly and voluntarily accept the ordinary risks of using software to control heated consumer hardware, including burns, spills, electrical injury, illness, permanent disability, serious bodily injury, death, fire, property damage, data loss, and damage to the mug, charger, Mac, or nearby objects. To the fullest extent permitted by law, you release the Developer from claims for property damage, bodily injury, or death arising from those inherent risks or from the Developer’s ordinary negligence in providing Swiftea. This includes claims arising from or related to software bugs, incorrect or unintended commands, communication failures, inaccurate readings, automation failures, or use of or inability to use Swiftea. This release does not apply to fraud, gross negligence or gross fault, recklessness, willful or intentional misconduct, violation of law, or any responsibility that cannot legally be waived.

## 13. Limitation of liability

TO THE FULLEST EXTENT PERMITTED BY LAW, THE DEVELOPER WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES; LOSS OF USE, DATA, PROFITS, OR OPPORTUNITY; OR DAMAGE CAUSED BY STALE READINGS, FAILED OR DELAYED COMMANDS, DISCONNECTIONS, AUTOMATION, NOTIFICATIONS, THIRD-PARTY HARDWARE, FIRMWARE, SERVICES, OR MODIFIED BUILDS. If the Developer is found liable despite these terms, total liability for all claims related to Swiftea will not exceed the greater of the amount you paid specifically for the prebuilt Swiftea app distributed by the Developer or US $10. These exclusions and this cap apply regardless of the legal theory asserted, including contract, tort (including ordinary negligence), strict liability, or statute, but only where applicable law permits. They apply to claims involving property damage, bodily injury, or death only where applicable law permits. This section does not apply to the Developer’s fraud, gross negligence or gross fault, recklessness, willful or intentional misconduct, violation of law, or any right or liability that cannot legally be excluded or limited, including under applicable consumer-protection or personal-injury law.

## 14. Third-party products and software

Swiftea depends on products and services outside the Developer’s control, including Ember hardware and firmware, Apple hardware and macOS, Core Bluetooth, GitHub infrastructure, and the Sparkle update framework. Their availability, behavior, terms, warranties, and privacy practices are their own. Swiftea’s acknowledgements identify open-source reference material and included third-party software.

## 15. Changes to these terms

The Developer may revise these terms when Swiftea, its risks, or applicable law changes. Swiftea will ask you to accept a materially revised version before continuing to use a prebuilt copy distributed by the Developer. Revised terms apply from their stated effective date. If you do not agree to a revised version, you may stop using and delete Swiftea. The version and effective date shown above identify the terms you accepted.

## 16. Rights that cannot be waived

These terms do not exclude, restrict, or waive any right, remedy, guarantee, warranty, or liability that applicable law does not permit to be excluded, restricted, or waived. If these terms conflict with such law, that law controls only to the extent of the conflict.

## 17. Governing law and general terms

California law governs these terms, without regard to conflict-of-law rules, to the extent permitted by applicable law. Courts located in California may hear disputes where legally permitted. If part of these terms is unenforceable, the rest remains in effect and the invalid part will be limited only as much as necessary. A failure to enforce one part is not a waiver. These terms, the Safety Notice, and the 0BSD license form the complete written understanding about prebuilt copies of Swiftea distributed by the Developer, while the 0BSD license remains controlling for source-code permissions.

## 18. Contact

The Developer is Tomás Papi. Questions about Swiftea can be raised through the public project at https://github.com/tomaspapi/swiftea. Do not post private device information, serial numbers, or other sensitive details in a public issue.
"""#

    static let safetyNoticeMarkdown = #"""
# Safety Notice

Swiftea controls a consumer product that heats liquids. Software convenience does not replace direct supervision and ordinary care.

**Version 1.0 · Effective July 18, 2026**

## Supervise the mug

Do not use Swiftea or a heated Ember Mug unattended, while sleeping, near flammable materials, or where children or pets can reach hot liquid or charging equipment. Keep the mug stable and use a temperature that is safe for the person drinking from it.

## Do not rely on the app as a safety control

Bluetooth, macOS sleep, another controller, firmware, or hardware can interrupt communication. Heating status, temperature, battery, charging, contents detection, notifications, history, automatic shutoff, and automatic reconnection may be delayed, inaccurate, or unavailable. Always verify the physical mug yourself.

## Software can behave unexpectedly

Swiftea is unofficial software and may contain bugs, defects, coding errors, omissions, or unintended behavior. It may send a delayed, repeated, incorrect, or unintended command; fail to send or stop a command; misread or misreport the mug’s state; or interact unexpectedly with the mug’s hardware or firmware. These events can occur even when you use Swiftea correctly and follow every instruction.

## Respond to unexpected behavior

If Swiftea and the mug disagree, or if the mug is damaged, leaking, unusually hot, smoking, producing an unusual smell, or behaving unpredictably, stop using it. Turn it off if safe, remove it from the charging coaster, move away from flammable materials, and follow Ember’s official support and safety guidance.

## Use and care for the hardware correctly

Never microwave an Ember Mug. Hand wash it as directed by Ember, dry it completely before charging, and use compatible official charging equipment. Follow Ember’s current manuals, warnings, care instructions, and recalls. Swiftea does not change or replace those instructions.

## Avoid competing controllers

Close other apps that may be connected to the mug. Competing controllers can cause disconnections, stale information, or commands that do not behave as expected.

## Your acknowledgment

By using Swiftea, you acknowledge and voluntarily accept that software bugs, defects, errors, omissions, unintended commands or effects, unreliable connections, unexpected hardware or firmware behavior, ordinary use, misuse, lack of supervision, and other expected or unexpected conditions can cause burns, spills, electrical hazards, fire, property damage, hardware damage, permanent disability, serious bodily injury, or death. These outcomes can occur even when you use Swiftea correctly and follow every instruction. You are responsible for deciding whether to use Swiftea, directly supervising the mug, operating it safely, and stopping use if anything appears unsafe or unexpected. This acknowledgment applies to the fullest extent permitted by law.
"""#

    static let privacyPolicyMarkdown = #"""
# Privacy Policy

Swiftea is developed by Tomás Papi (the “Developer”). It is designed to control your Ember Mug without an account, a cloud service, ads, or developer-operated tracking. Mug information stays on your Mac. The Developer does not receive your mug readings, history, names, or identifiers. This policy explains what Swiftea handles locally, when it connects to the internet, and what choices you have.

**Version 1.0 · Effective July 20, 2026**

## At a glance

Swiftea has no account or sign-in, developer-operated advertising, analytics, telemetry, cross-site tracking, or cloud upload of mug readings or history. The Developer does not sell or rent personal information. Mug history stays on your Mac for up to 30 days. Internet access is limited to software updates, the Swiftea website, and links you choose to open.

## Information handled on your Mac

Swiftea uses Bluetooth to find, connect to, and control compatible mugs. To do that, the app may process device identifiers and advertised Bluetooth information; mug details such as its name, model, color, size, and serial number; and live readings such as temperature, battery, charging, contents, connection, and heating state.

Swiftea also stores preferences and app state locally, including saved mugs, mug aliases, auto-connect choices, target temperatures, display settings, notification choices, and records showing which versions of the Terms of Use and Safety Notice you accepted.

Battery and temperature history is stored in your Mac’s Application Support folder. History is separated by mug and automatically pruned after 30 days. Native notifications are created on your Mac when you enable them. Diagnostic logs are local and managed by macOS; Swiftea does not upload them, and device-specific details are treated as private by default.

The Developer cannot remotely access this local information.

## Software updates

When automatic update checks are enabled, or when you check manually, Swiftea uses Sparkle to request its public update feed from GitHub Pages and may download an update from GitHub Releases. Swiftea does not send mug names, serial numbers, readings, history, or Bluetooth identifiers with these requests, and it does not opt in to Sparkle’s optional system-profile reporting.

As with an ordinary web request, GitHub may receive network information needed to deliver the feed or file, such as your IP address, the requested URL, request time, and basic request or device metadata. GitHub handles that information under the GitHub Privacy Statement at https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement.

## Website

The Swiftea website does not contain Developer-operated analytics, advertising, or tracking code. It is hosted by GitHub Pages. GitHub states that it logs and stores visitors’ IP addresses for security purposes, whether or not a visitor is signed in. This logging is performed by GitHub as the website host, not by a tracker added by Swiftea. The Developer does not receive mug data through the website.

If you follow a link to GitHub or another external website, that service’s own privacy practices apply. Swiftea is not responsible for third-party websites or services.

## Sharing and sale

The Developer does not sell, rent, or share your mug information or app activity for advertising, profiling, or analytics. Swiftea does not have a backend that receives this information. Infrastructure providers may receive the limited network information described above when they deliver the website, update feed, or app download.

## Retention and deletion

Mug history is automatically deleted after 30 days. Other locally stored preferences and saved mug details remain on your Mac until you change them, forget a mug, or delete Swiftea’s local data. Forgetting a mug removes its saved connection details and alias; any existing history for that mug continues to age out under the 30-day limit.

Deleting the app alone may not remove its local data. To erase Swiftea’s remaining local data, quit Swiftea and remove ~/Library/Application Support/Swiftea and ~/Library/Preferences/com.tom.swiftea.plist.

The Developer has no Swiftea account record or server-side mug data to access or delete.

## Permissions and choices

Bluetooth access is required to discover and control a mug. Notification access is optional and can be changed in macOS System Settings. Automatic update checks can be turned off in Swiftea’s Settings.

The Swiftea website does not perform cross-site tracking, so it does not change its behavior in response to “Do Not Track” signals.

## Children’s privacy

Swiftea is not directed to children under 13, and the Developer does not knowingly collect personal information from children through Swiftea.

## Security

Keeping mug information on your Mac reduces the amount of data exposed to online services, but no software or device is perfectly secure. Keep macOS up to date and protect access to your Mac.

## Changes to this policy

This policy may be updated when Swiftea’s features or privacy practices change. Material changes will be posted on the Swiftea website and reflected in the policy available inside the app. The effective date at the top will be updated when a revised policy is published. If a future change requires consent under applicable law, Swiftea will request it before the affected feature is used.

## Contact

Swiftea is developed by Tomás Papi. Privacy questions can be raised through the Swiftea project at https://github.com/tomaspapi/swiftea. Do not include mug serial numbers, logs, or other sensitive information in a public issue.
"""#

    static let acknowledgementsMarkdown = #"""
# Acknowledgements

Swiftea is an independent app for controlling an Ember Mug over Bluetooth. It is not affiliated with, sponsored by, authorized by, or endorsed by Ember Technologies, Inc.

Ember, Ember Mug, Ember Mug 2, and related names and marks are trademarks or property of their respective owners.

Swiftea’s Bluetooth implementation was informed by public reverse-engineering notes and prior open-source Ember mug projects, including:

- [orlopau/ember-mug](https://github.com/orlopau/ember-mug) — Paul Orlob
- [sopelj/python-ember-mug](https://github.com/sopelj/python-ember-mug) — Jesse Sopel
- [sopelj/hass-ember-mug-component](https://github.com/sopelj/hass-ember-mug-component) — Jesse Sopel and contributors
- [importRyan/Muggle](https://github.com/importRyan/Muggle) — Ryan Ferrell

These projects were used as public reference material; they are not included inside Swiftea.

## Included open-source software

- [sparkle-project/Sparkle](https://github.com/sparkle-project/Sparkle) — Sparkle Project contributors

Sparkle is included in Swiftea to support direct-download app updates. Its license notice is bundled with the app.
"""#

    static let licenseText = #"""
Zero-Clause BSD

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
"""#
}
