#!/usr/bin/env swift

import Foundation

private struct SourceDocument {
    let propertyName: String
    let fileName: String
}

private let documents = [
    SourceDocument(propertyName: "termsOfUseMarkdown", fileName: "TERMS_OF_USE.md"),
    SourceDocument(propertyName: "safetyNoticeMarkdown", fileName: "SAFETY_NOTICE.md"),
    SourceDocument(propertyName: "privacyPolicyMarkdown", fileName: "PRIVACY_POLICY.md"),
    SourceDocument(propertyName: "acknowledgementsMarkdown", fileName: "ACKNOWLEDGEMENTS.md"),
    SourceDocument(propertyName: "licenseText", fileName: "LICENSE")
]

private let scriptURL = URL(fileURLWithPath: #filePath)
private let rootURL = scriptURL
    .deletingLastPathComponent()
    .deletingLastPathComponent()
private let outputURL = rootURL
    .appendingPathComponent("Sources/Swiftea/Support/GeneratedLegalDocumentSources.swift")
private let shouldCheck = Array(CommandLine.arguments.dropFirst()) == ["--check"]

private func normalizedContents(of document: SourceDocument) throws -> String {
    let url = rootURL.appendingPathComponent(document.fileName)
    var source = try String(contentsOf: url, encoding: .utf8)
        .replacingOccurrences(of: "\r\n", with: "\n")

    while source.hasSuffix("\n") {
        source.removeLast()
    }

    return source
}

private func rawStringLiteral(for source: String) -> String {
    var delimiterCount = 1

    while source.contains("\"\"\"" + String(repeating: "#", count: delimiterCount)) {
        delimiterCount += 1
    }

    let hashes = String(repeating: "#", count: delimiterCount)
    return "\(hashes)\"\"\"\n\(source)\n\"\"\"\(hashes)"
}

private func generatedSource() throws -> String {
    var lines = [
        "// Generated by script/generate_legal_documents.swift.",
        "// Edit the canonical root documents, then run the generator.",
        "",
        "enum GeneratedLegalDocumentSources {"
    ]

    for (index, document) in documents.enumerated() {
        let source = try normalizedContents(of: document)
        let literal = rawStringLiteral(for: source)
        lines.append("    static let \(document.propertyName) = \(literal)")

        if index < documents.count - 1 {
            lines.append("")
        }
    }

    lines.append("}")
    lines.append("")
    return lines.joined(separator: "\n")
}

do {
    let expected = try generatedSource()

    if shouldCheck {
        let existing = try String(contentsOf: outputURL, encoding: .utf8)
        guard existing == expected else {
            FileHandle.standardError.write(
                Data("Generated legal-document source is stale. Run script/generate_legal_documents.swift.\n".utf8)
            )
            exit(1)
        }

        print("Generated legal-document source matches the canonical documents.")
    } else {
        try Data(expected.utf8).write(to: outputURL, options: .atomic)
        print("Updated \(outputURL.path)")
    }
} catch {
    FileHandle.standardError.write(Data("Legal-document generation failed: \(error)\n".utf8))
    exit(1)
}
